[build.targets.wheel]
only-include = ["src/pydra/tasks/ants"]
sources = ["src"]

[envs.default]
dependencies = ["pytest"]
[envs.default.scripts]
test = "pytest {args}"

[[envs.all.matrix]]
python = ["3.7", "3.8", "3.9", "3.10", "3.11"]
